---
title: "sandbox"
format: html
---
```{r setup}
#| include: false
library(readr)
library(here)
library(tidyverse)
library(targets)
library(snakecase)
tar_config_set(store = here::here("_targets"))
source(here::here("R/functions.R"))
```

## Reading data

```{r}
lipoproteins <- readr::read_csv(here::here("data/Metabolites_dragons_with_lipoproteins.csv"),
  show_col_types = FALSE,
  name_repair = to_snake_case
)
```
## Creating table with descriptive statistics
First removing unwanted data and then transforming data to long format
```{r}
# Preprocessing
lipoproteins |>
  select(
    -c(grade, other_liver_disease, weight, age, hu, fat_perc, fibrosis_perc, uric_acid)
  ) |>
  pivot_longer(
    cols = -c(id, lipidosis)
  ) |>
  rename("metabolite" = name)

# Preprocess function
preprocess <- function(data) {
  data |>
    dplyr::select(
      -c(grade, other_liver_disease, weight, age, hu, fat_perc, fibrosis_perc, uric_acid)
    ) |>
    tidyr::pivot_longer(
      cols = -c(id, lipidosis)
    ) |>
    dplyr::rename("metabolite" = name)
}
```
Now the statistics table can be created:
```{r}
lipoproteins |>
  preprocess() |>
  summarise(
    across(
      -c(id, lipidosis),
      list(
        mean = mean, sd = sd, median = median,
        iqr = \(x) IQR(x, na.rm = TRUE)
      )
    ),
    .by = c(metabolite)
  ) |>
  filter(!is.na(c(value_sd))) |>
  mutate(across(where(is.numeric), \(x) round(x, digits = 1))) |>
  mutate(MeanSD = glue::glue("{value_mean} ({value_sd})")) |>
  mutate(MedianIQR = glue::glue("{value_median} ({value_iqr})")) |>
  select(Metabolite = metabolite, "Mean (SD)" = MeanSD, "Median (IQR)" = MedianIQR)

# Generalising into a function
create_table_descriptive_stats <- function(data) {
  data |>
    preprocess() |>
    dplyr::summarise(
      dplyr::across(
        -c(id, lipidosis),
        list(
          mean = mean, sd = sd, median = median,
          iqr = \(x) IQR(x, na.rm = TRUE)
        )
      ),
      .by = c(metabolite)
    ) |>
    dplyr::filter(!is.na(c(value_sd))) |>
    dplyr::mutate(across(where(is.numeric), \(x) round(x, digits = 1))) |>
    dplyr::mutate(MeanSD = glue::glue("{value_mean} ({value_sd})")) |>
    dplyr::mutate(MedianIQR = glue::glue("{value_median} ({value_iqr})")) |>
    dplyr::select(Metabolite = metabolite, "Mean (SD)" = MeanSD, "Median (IQR)" = MedianIQR)
}
create_table_descriptive_stats(lipoproteins)
```

# Creating plot to show distributions
```{r}
lipoproteins |>
  preprocess() |>
  filter(metabolite %in% c("insulin", "hdl", "ldl", "chol", "na", "k", "cl", "ca", "phosphate")) |>
  ggplot(aes(x = value)) +
  geom_histogram() +
  facet_wrap(vars(metabolite), scales = "free") +
  theme(
    plot.title = element_text(hjust = 0.5)
  ) +
  labs(
    x = "Metabolite value",
    y = "Count",
    title = "Metabolite value distributions"
  )

# Turning it into a generalised function

#' Create a plot showing metabolite distributions
#'
#' @param data Lipoproteins data set.
#'
#' @returns Plot showing metabolite distributions.
create_plot_distributions <- function(data) {
  data |>
    preprocess() |>
    dplyr::filter(metabolite %in% c("insulin", "hdl", "ldl", "chol", "na", "k", "cl", "ca", "phosphate")) |>
    ggplot2::ggplot(ggplot2::aes(x = value)) +
    ggplot2::geom_histogram() +
    ggplot2::facet_wrap(ggplot2::vars(metabolite), scales = "free") +
    ggplot2::theme(
      plot.title = ggplot2::element_text(hjust = 0.5)
    ) +
    ggplot2::labs(
      x = "Metabolite value",
      y = "Count",
      title = "Metabolite value distributions"
    )
}
```

# Running model on one metabolite

First preparing data for analysis
```{r}
lipoproteins |>
  preprocess() |>
  mutate(
    lipidosis = as.factor(lipidosis),
    value = as.vector(scale(value))
  )
# Turning it into generalised function

#' Making data ready for running model
#'
#' @param data Data set with lipoproteins.
#'
#' @returns Ready data set for model analysis.

ready_data <- function(data) {
  data |>
    preprocess() |>
    dplyr::mutate(
      lipidosis = as.factor(lipidosis),
      value = as.vector(scale(value))
    )
}
ready_data(lipoproteins)
```

```{r}
just_insulin <- lipoproteins |>
  ready_data() |>
  filter(metabolite == "insulin")

glm(
  formula = lipidosis ~ value,
  data = just_insulin,
  family = binomial
) |>
  broom::tidy(exponentiate = TRUE) |>
  mutate(
    metabolite = unique(just_insulin$metabolite),
    model = format(lipidosis ~ value),
    .before = everything()
  )

# Making generalised function

#' Function to test model on a single metabolite
#'
#' @param data Lipoproteins data set.
#'
#' @returns Data frame with coefficients, sd and p val.
fit_model <- function(data) {
  glm(
    formula = lipidosis ~ value,
    data = data,
    family = binomial
  ) |>
    broom::tidy(exponentiate = TRUE) |>
    dplyr::mutate(
      metabolite = unique(data$metabolite),
      model = format(lipidosis ~ value),
      .before = tidyselect::everything()
    )
}

#' Create model results
#'
#' @param data Lipidomics data
#'
#' @returns Data frame with model results for insulin metabolite
create_model_results <- function(data) {
  data |>
    ready_data() |>
    dplyr::group_split(metabolite) |>
    purrr::map(fit_model) |>
    purrr::list_rbind()
}
create_model_results(lipoproteins)
```

# Plotting model results
```{r}
model_results <- create_model_results(lipoproteins)

#' Plot the estimates and standard errors of the model results
#'
#' @param results The model results.
#'
#' @returns A ggplot2 figure.
create_plot_model_results <- function(results) {
  results |>
    dplyr::filter(term == "value", std.error <= 2, estimate <= 5) |>
    dplyr::select(metabolite, model, estimate, std.error) |>
    ggplot2::ggplot(ggplot2::aes(
      x = estimate,
      y = metabolite,
      xmin = estimate - std.error,
      xmax = estimate + std.error
    )) +
    ggplot2::geom_pointrange() +
    ggplot2::geom_vline(xintercept = 1, linetype = "dashed") +
    ggplot2::facet_grid(cols = ggplot2::vars(model))
}
create_plot_model_results(model_results)


```
